steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/hallowed-trail-385003/cloud-build-trigger','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/hallowed-trail-385003/cloud-build-trigger']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy','cbt-cloud-run','--image','gcr.io/hallowed-trail-385003/cloud-build-trigger','--port','0.0.0.0','--region','us-central1','--platform','managed','--allow-unauthenticated']

